name: CircleCI -> Heroku

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    docker:
      - image: node:16
    env: 
      SECRET: ${{ secrets.SECRET }}
      REFRESH_SECRET: ${{ secrets.REFRESH_SECRET }}
      UPDATE_SECRET: ${{ secrets.UPDATE_SECRET }}
      UPDATE_REFRESH_SECRET: ${{ secrets.UPDATE_REFRESH_SECRET }}
      ADMIN: ${{ secrets.ADMIN }}
      PASSWORD: ${{ secrets.PASSWORD }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
      GOOGLE_SEND_EMAIL_PASSWORD: ${{ secrets.GOOGLE_SEND_EMAIL_PASSWORD }}
      MONGO_DB: ${{ secrets.MONGO_DB }}

    steps:
      - checkout 
      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Deploy to Heroku
          command: |
            echo "${HEROKU_API_KEY}" | docker login -u _ --password-stdin registry.heroku.com
            docker build -t registry.heroku.com/${HEROKU_APP_NAME}/web .
            docker push registry.heroku.com/${HEROKU_APP_NAME}/web